

<?php
$title = 'Add Veranstalter';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php if(!empty($message)) echo sprintf($message)?>
 
 <?php if ($this->error): ?>
           <p class="error">There were one or more issues with your
		Login. Please correct them as indicated below.</p>
<?php endif ?>

 <?php
	$form = $this->form;
	$form->prepare ();
	$form->setAttribute ( 'action', $this->url( 'veranstalter', array ('action' => 'add' ) ) );
	$form->setAttribute ( 'method', 'post' );
	echo $this->form ()->openTag ( $form );
	?>
	
	  <dl class="zend_form">
		
		
		
		<dt><?php echo $this->formLabel($form->get('company')); ?></dt>
        <dd><?php
			echo $this->formElement ( $form->get ( 'company' ) );
			echo $this->formElementErrors ( $form->get ( 'company' ) );
		?></dd>
		
		
		<dt><?php echo $this->formLabel ( $form->get ( 'street_address' ) );?></dt>
		<dd><?php
			echo $this->formElement ( $form->get ( 'street_address' ) );
			echo $this->formElementErrors ( $form->get ( 'street_address' ) );
		?></dd>
		
		<dt><?php echo $this->formLabel ( $form->get ( 'house_number' ) );?></dt>
		<dd><?php
			echo $this->formElement ( $form->get ( 'house_number' ) );
			echo $this->formElementErrors ( $form->get ( 'house_number' ) );
		?></dd>
		

		
		<dd><?php
			echo $this->formElement ( $form->get ( 'submit' ) );
			echo $this->formElementErrors ( $form->get ( 'submit' ) );
		?></dd>
	</dl>
	


<?php echo $this->form()->closeTag() ?>

 