<?php use Zend\Session\Container;
echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Starmina '. $this->translate('Sports Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Zend Framework 2"/></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('veranstalter', array('action'=>'index') )?>"><?php echo $this->translate('Veranstalter') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('users', array('action'=>'index') )?>"><?php echo $this->translate('UserController') ?></a></li>
                    </ul>
                    <?php 
                    $session= new Container('userSession');
                    if(!$session->offsetExists('user')){?>
                    <form class="navbar-form navbar-right form-horizontal" role="search" method="post" action="users/login">
       					 <div class="form-group" >
       					 		<a href="http://facebook.com" class="fb-button col-md-2"></a>
        					  <div class="col-md-5"><input type="email" class="form-control" placeholder="E-Mail"></div>
        					 <div class="col-md-5"> <input type="password" class="form-control" placeholder="Passwort"></div>
        					
       					 </div>
       					 <button type="submit" class="btn btn-primary">Login</button>
     				 </form>
                    <?php }else{?>
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('users') ?>"><?php echo $this->translate($session->offsetGet('user')->getName()) ?></a></li>
                    </ul>
                 <?php }?>
                    
                </div><!--/.nav-collapse -->
         </div>
        </nav>
        <div class="container">
        	<div class="maincontent">
            <?php echo $this->content; ?>
            </div>
            <hr>
             <footer class="footer">
            <p>&copy; 2014 - <?php echo date('Y') ?> by Starmina</p>
            	<div class="row">
	            	<div class="col-md-6 col-md-offset-3">
	            		<div class="text-center">
	        		    	<a>Karriere bei Stamina            ------</a><a>Impressum            ------</a>
		                	<a>Ueber Stamina</a>
	                </div></div>
                </div>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
