
	<div class="row center-block" id="indexwelcome">
		<div class="col-md-8">
			<div class="welcome">
			<h1>Starmina</h1>
			<h2> ... und alle so yeah!</h2>
			</div>
		</div>
		<div class="col-md-4">
			<div class="reg-short">
			<?php if ($this->error): ?><p class="error">There were one or more issues with your submission. Please correct them as indicated below.</p>
			<?php endif ?>

			<?php
             $form = $this->form;
             $form->prepare();
             $form->setAttribute('action', $this->url('users', array('action' => 'register')));
             $form->setAttribute('method', 'post');
             echo $this->form()->openTag($form);
             ?>
					<div class="form-group">
						<div class="col-xs-12">
						<dl class="zend_form">
												
						<dt><?php echo $this->formLabel($form->get('name')); ?></dt> 
						<dd><?php 
								  echo $this->formElement ( $form->get ( 'name' ) );
								  
						?></dd>
						
						<dt><?php echo $this->formLabel($form->get('surname')); ?></dt> 
						<dd><?php
								echo $this->formElement ( $form->get ( 'surname' ) );
								
							?></dd>
						
						<dt><?php echo $this->formLabel($form->get('email')); ?></dt>
       					<dd><?php echo $this->formElement ( $form->get( 'email' ) );
								
							?></dd>
		
		
		<dt><?php echo $this->formLabel ( $form->get( 'password') );?></dt>
		<dd><?php
			echo $this->formElement ( $form->get( 'password' ) );
		
		?></dd>
		
		
		<dt><?php echo $this->formLabel ( $form->get( 'confirm_password' ));?></dt>
		<dd><?php
			echo $this->formElement ( $form->get('confirm_password') );
		
		?></dd>
		
		<dt><?php echo $this->formLabel ( $form->get( 'roles_ID' ));?></dt>
		<dd><?php
			echo $this->formElement ( $form->get('roles_ID') );
		
		?></dd>
	
		
		<dd><?php
			echo $this->formElement ( $form->get ('submit') );
		
		?></dd>
	</dl>
	



						</div>
					</div>
		<?php echo $this->form()->closeTag() ?>		
				
		</div>
	</div>
	</div>
	<div class="row center-block grey-content">
		<div class="col-md-12">
			<p>Kleine Anmerkung zum Pushen: Wenn ihr was pusht, dann bitte nur die veränderten Dateien und nicht immer alles ! </p>
		</div>
	</div>
	<div class="row center-block white-content">
	   <div class="col-md-4">
                <h3><?php echo $this->translate('Follow Development') ?></h3>
                <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p>
        </div>
   		<div class="col-md-4">
                <h3><?php echo $this->translate('Discover Modules') ?></h3>
                <p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>

    	</div>
    	<div class="col-md-4">
                <h3><?php echo $this->translate('Help &amp; Support') ?></h3>
                <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
    	</div>
	</div>
